version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    groups:
      production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "weekly"
